"""add email verification columns

Revision ID: 59e32273c7c0
Revises: c410963cea00
Create Date: 2025-12-02 13:05:52.852177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '59e32273c7c0'
down_revision: Union[str, Sequence[str], None] = 'c410963cea00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
   
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.true())
    )

   
    op.execute("UPDATE users SET is_verified = TRUE;")


    op.alter_column('users', 'is_verified', server_default=None)

    
    op.add_column(
        'users',
        sa.Column('verification_token', sa.String(), nullable=True)
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
