"""birth_year_silindi_birth_date_eklendi

Revision ID: 7f98042bf759
Revises: 540d76f23612
Create Date: 2025-12-07 14:41:54.166929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f98042bf759'
down_revision: Union[str, Sequence[str], None] = '540d76f23612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint_photos', 'complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_complaint_photos_id'), 'complaint_photos', ['id'], unique=False)
    op.drop_constraint(op.f('complaint_photos_complaint_id_fkey'), 'complaint_photos', type_='foreignkey')
    op.create_foreign_key(None, 'complaint_photos', 'complaints', ['complaint_id'], ['id'])
    op.drop_column('users', 'birth_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'complaint_photos', type_='foreignkey')
    op.create_foreign_key(op.f('complaint_photos_complaint_id_fkey'), 'complaint_photos', 'complaints', ['complaint_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_complaint_photos_id'), table_name='complaint_photos')
    op.alter_column('complaint_photos', 'complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
